import { vpc } from "./networking";

// Holds the .docx source files that Bedrock ingests into the Knowledge Base
const kbBucket = new sst.aws.Bucket("KbDocuments");

// Aurora Serverless v2 cluster — vector store backing the Bedrock Knowledge Base via pgvector
const rds = new sst.aws.Aurora("VectorStore", {
  engine: "postgres",
  dataApi: true, // required for Bedrock KnowledgeBase to access RDS
  vpc,
  scaling: { min: "0.5 ACU", max: "1 ACU" },
});

// Persists Strands agent sessions (conversation history + manager state) across Lambda invocations.
// Keyed by session_id generated by the frontend and passed on every chat request.
// S3 chosen over Redis (overkill, always-on cost) and AgentCore Memory (cross-session LTM,
// wrong abstraction for within-session continuity).
const sessionsBucket = new sst.aws.Bucket("AgentSessions");

// Expire sessions older than 30 days to control storage costs
new aws.s3.BucketLifecycleConfigurationV2("AgentSessionsLifecycle", {
  bucket: sessionsBucket.nodes.bucket.id,
  rules: [
    {
      id: "expire-old-sessions",
      status: "Enabled",
      expiration: { days: 30 },
    },
  ],
});

// Stores restaurant reservations
const table = new sst.aws.Dynamo("Bookings", {
  fields: {
    booking_id: "string",
    user_id: "string",
    restaurant_name: "string",
    date: "string",
  },
  primaryIndex: { hashKey: "booking_id", rangeKey: "restaurant_name" },
  globalIndexes: {
    // Enables queries like "all bookings at Restaurant X on date Y" without a full table scan
    ByRestaurantDate: {
      hashKey: "restaurant_name",
      rangeKey: "date",
    },
    // Enables queries like "all bookings for user X"
    ByUser: {
      hashKey: "user_id",
      rangeKey: "date",
    },
  },
});

export { table, kbBucket, rds, sessionsBucket };
